Changed the testcase directory finding mechanism to look for a yaml formatted configuration file and added support for parsing basic options specified in that file.  Basic test running support also added.

diff --git a/dummy/failing_test/test b/dummy/failing_test/test
--- a/dummy/failing_test/test
+++ b/dummy/failing_test/test
@@ -1,3 +1,4 @@
 #!/bin/sh
 
-echo "Dummy passing test"
+echo "Dummy failing test"
+exit 1
